on: [ push ]

jobs:
  migration_job:
    runs-on: ubuntu-latest
    name: CI migration
    steps:
      - name: DB migration with DLE
        uses: agneum/migration-action@v0.0.7
        id: db-migration
        with:
          dbname: test
          commands:  |
            env
            flyway -url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE} migrate
            flyway -url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE} info
            echo 'Migration has been completed'
          migration_envs: |
            DATABASE_LAB_CI=true
            FLYWAY_USER=$PGUSER
            FLYWAY_PASSWORD=$PGPASSWORD
            FLYWAY_LOCATIONS=filesystem:/flyway/sql
            FLYWAY_CONNECT_RETRIES=60
        env:
          CI_ENDPOINT: ${{ secrets.CI_ENDPOINT }}
          SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
      - name: Get the response status
        run: echo "${{ steps.db-migration.outputs.response }}"
