on: [ push ]

jobs:
  migration_job:
    runs-on: ubuntu-latest
    name: CI migration
    steps:
      - name: DB migration with DLE
        uses: agneum/migration-action@v0.0.7
        id: db-migration
        with:
          dbname: test
          commands:  |
            env
            flyway -url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE} -user=${PGUSER} -password=${PGPASSWORD} -locations=filesystem:/repo/flyway/sql migrate
            flyway -url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE} -user=${PGUSER} -password=${PGPASSWORD} -locations=filesystem:/repo/flyway/sql info
          migration_envs: |
            DATABASE_LAB_CI=true
            FLYWAY_CONNECT_RETRIES=60
            FLYWAY_BASELINE_ON_MIGRATE=true
        env:
          CI_ENDPOINT: ${{ secrets.CI_ENDPOINT }}
          SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
      - name: Get the response status
        run: echo "${{ steps.db-migration.outputs.response }}"
